### ISSUE TITLE
how to check for nexell support in libdrm?

### ISSUE THREAD

**Issue by erazor83** [SamsungARTIK/libdrm#1]
Hi there.

Sorry for asking this here but I've no idea how to start.

I got a S5P4418 board and am trying to get Wayland/Weston with drm to run.

My system is gentoo and I'm compiling native on the device. I also patched and recompiled my libdrm to support the nexell chip.

Any idea how I can debug if libdrm actually is able to use the nexell chip? Just trying to start weston with the drm interface does not help me much since it simply fails without helpful information.

Thanks a lot.

**Comment by cometzero** [comment]
Hi,
Did you have nexell drm driver of your s5p4418 kernel?

**Comment by erazor83** [comment]
Well, I'm not quite sure about it.

I don't have DRM support (Direct Rendering Manager (XFree86...)).

Instead there is a seperate menu called "Nexell Graphics"
  * Allocate framebuffer with ION
  * Support primary frame buffer (/dev/fb0)
  * LCD

On V4L2 I also got some Nexell stuff
  * Video capture interface
  * Nexell M2M interface
  * Nexell OUT interface

So I assume I probably lack the DRM support for Nexell already in my kernel?

**Comment by cometzero** [comment]
You might use the nexell 3.4 kernel. As I know, it does not support DRM driver. So, you can't use this libdrm until you port the nexell arm in your kernel.
